<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="73652" started-at="2020-01-23T18:51:58Z" finished-at="2020-01-23T18:53:11Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="73652" started-at="2020-01-23T18:51:58Z" finished-at="2020-01-23T18:53:11Z">
      <class name="com.salesforce.test.website.CreateObjectTest">
        <test-method status="PASS" signature="beforeSuite(java.lang.String)[pri:0, instance:com.salesforce.test.website.CreateObjectTest@15d0c81b]" name="beforeSuite" is-config="true" duration-ms="15" started-at="2020-01-24T00:21:58Z" finished-at="2020-01-24T00:21:58Z">
          <params>
            <param index="0">
              <value is-null="true"/>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.salesforce.test.website.CreateObjectTest@15d0c81b]" name="setUp" is-config="true" duration-ms="18017" started-at="2020-01-24T00:21:58Z" finished-at="2020-01-24T00:22:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="createAContactAndDeleteTest()[pri:0, instance:com.salesforce.test.website.CreateObjectTest@15d0c81b]" name="createAContactAndDeleteTest" duration-ms="54011" started-at="2020-01-24T00:22:16Z" finished-at="2020-01-24T00:23:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Contact is not created expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Contact is not created expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.salesforce.test.website.CreateObjectTest.createAContactAndDeleteTest(CreateObjectTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createAContactAndDeleteTest -->
        <test-method status="PASS" signature="tearDownSession()[pri:0, instance:com.salesforce.test.website.CreateObjectTest@15d0c81b]" name="tearDownSession" is-config="true" duration-ms="1095" started-at="2020-01-24T00:23:10Z" finished-at="2020-01-24T00:23:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownSession -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.salesforce.test.website.CreateObjectTest@15d0c81b]" name="afterSuite" is-config="true" duration-ms="215" started-at="2020-01-24T00:23:11Z" finished-at="2020-01-24T00:23:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.salesforce.test.website.CreateObjectTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
